prepare:
  features:
    - sepal length (cm)
    - sepal width (cm)
    - petal length (cm)
    - petal width (cm)
  test_size: 0.9

train:
  model: AdaBoostClassifier

eval:
  metrics:
  - precision
  - recall
  - accuracy
